# https://docs.github.com/ja/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "./.github/workflows"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "⬆️ "
      prefix-development: "⬆️ "
    pull-request-branch-name:
      separator: "/"
    labels:
      - "dependencies"
      - "github-actions"

  - package-ecosystem: "terraform"
    directory: "./terraform"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "⬆️ "
      prefix-development: "⬆️ "
    pull-request-branch-name:
      separator: "/"
    labels:
      - "dependencies"
      - "terraform"
